list: $/learnkit/entree/models/loginlog/columns.yaml
modelClass: LearnKit\Entree\Models\LoginLog
title: LoginLogs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'learnkit/entree/loginlogs/preview/:id'
